# Generated by Django 4.1.12 on 2023-10-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loudness', '0003_alter_loudness_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loudness',
            options={'verbose_name': '响度数据', 'verbose_name_plural': '响度数据'},
        ),
        migrations.AlterField(
            model_name='loudness',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工况'),
        ),
        migrations.AlterField(
            model_name='loudness',
            name='image',
            field=models.FileField(blank=True, default=' ', null=True, upload_to='upload_image'),
        ),
        migrations.AlterField(
            model_name='loudness',
            name='left',
            field=models.FloatField(blank=True, null=True, verbose_name='响度左耳-sone'),
        ),
        migrations.AlterField(
            model_name='loudness',
            name='right',
            field=models.FloatField(blank=True, null=True, verbose_name='响度右耳-sone'),
        ),
        migrations.AlterField(
            model_name='loudness',
            name='speed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='速度形式'),
        ),
        migrations.AlterField(
            model_name='loudness',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='荷载状态'),
        ),
    ]
