# Generated by Django 4.0.5 on 2023-12-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('brand', models.CharField(max_length=50, verbose_name='汽车品牌')),
                ('speed', models.CharField(max_length=50, verbose_name='速度形式')),
                ('condition', models.CharField(max_length=100, verbose_name='工况')),
                ('status', models.CharField(max_length=100, verbose_name='荷载状态')),
                ('clarity_left', models.FloatField(blank=True, null=True, verbose_name='语音清晰度度左耳-%')),
                ('clarity_right', models.FloatField(blank=True, null=True, verbose_name='语音清晰度度右耳-%')),
                ('clarity', models.FloatField(blank=True, null=True, verbose_name='语音清晰度度-%')),
                ('loudness_left', models.FloatField(blank=True, null=True, verbose_name='响度左耳-sone')),
                ('loudness_right', models.FloatField(blank=True, null=True, verbose_name='响度右耳-sone')),
                ('loudness', models.FloatField(blank=True, null=True, verbose_name='响度-sone')),
                ('sharpness_left', models.FloatField(verbose_name='尖锐度左耳-acum')),
                ('sharpness_right', models.FloatField(verbose_name='尖锐度右耳-acum')),
                ('sharpness', models.FloatField(blank=True, null=True, verbose_name='尖锐度-acum')),
                ('volatility_left', models.FloatField(verbose_name='波动度左耳-vacil')),
                ('volatility_right', models.FloatField(verbose_name='波动度右耳-vacil')),
                ('volatility', models.FloatField(verbose_name='波动度-vacil')),
                ('index', models.FloatField(default=0, verbose_name='声品质综合评价指数')),
            ],
            options={
                'verbose_name': '结果总表',
                'verbose_name_plural': '结果总表',
                'db_table': 'total',
            },
        ),
    ]
