# Generated by Django 4.0.5 on 2023-12-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total',
            old_name='image',
            new_name='data_image',
        ),
        migrations.RenameField(
            model_name='total',
            old_name='result',
            new_name='data_result',
        ),
    ]
