# Generated by Django 4.0.5 on 2023-12-08 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_options_alter_car_brand_alter_car_gear_and_more'),
        ('total', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='totaldata',
            name='brand',
        ),
        migrations.AddField(
            model_name='totaldata',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='汽车品牌'),
        ),
        migrations.AddField(
            model_name='totaldata',
            name='result',
            field=models.FloatField(blank=True, null=True, verbose_name='通过噪声最终结果'),
        ),
    ]
