# Generated by Django 4.0.5 on 2023-12-08 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_options_alter_car_brand_alter_car_gear_and_more'),
        ('total', '0002_remove_totaldata_brand_totaldata_car_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TotalData',
            new_name='Total',
        ),
    ]
