# Generated by Django 4.0.5 on 2023-12-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0004_rename_clarity_total_clarity_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='clarity_image',
            field=models.FileField(default=' ', upload_to='upload_image', verbose_name='语音清晰度图片地址'),
        ),
        migrations.AlterField(
            model_name='total',
            name='data_image',
            field=models.FileField(default=' ', upload_to='upload_image', verbose_name='声压级图片地址'),
        ),
        migrations.AlterField(
            model_name='total',
            name='loudness_image',
            field=models.FileField(default=' ', upload_to='upload_image', verbose_name='响度图片地址'),
        ),
        migrations.AlterField(
            model_name='total',
            name='sharpness_image',
            field=models.FileField(default=' ', upload_to='upload_image', verbose_name='尖锐度图片地址'),
        ),
        migrations.AlterField(
            model_name='total',
            name='volatility_image',
            field=models.FileField(default=' ', upload_to='upload_image', verbose_name='波动度图片地址'),
        ),
    ]
