# Generated by Django 4.0.5 on 2023-12-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0004_alter_total_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='total',
            name='clarity',
            field=models.FloatField(blank=True, null=True, verbose_name='语音清晰度-%'),
        ),
        migrations.AlterField(
            model_name='total',
            name='clarity_left',
            field=models.FloatField(blank=True, null=True, verbose_name='语音清晰度左耳-%'),
        ),
        migrations.AlterField(
            model_name='total',
            name='clarity_right',
            field=models.FloatField(blank=True, null=True, verbose_name='语音清晰度右耳-%'),
        ),
    ]
