# Generated by Django 4.0.5 on 2023-09-21 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
        ('loudness', '0001_initial'),
        ('volatility', '0001_initial'),
        ('clarity', '0001_initial'),
        ('sharpness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('speed', models.CharField(max_length=50, verbose_name='速度形式')),
                ('power', models.CharField(max_length=50, verbose_name='动力形式')),
                ('condition', models.CharField(max_length=100, verbose_name='工况')),
                ('status', models.CharField(max_length=100, verbose_name='荷载状态')),
                ('first_left', models.FloatField(verbose_name='测量次数一AA-BB内最大声压级（左侧）-SPL_L')),
                ('first_right', models.FloatField(verbose_name='测量次数一AA-BB内最大声压级（右侧）-SPL_R')),
                ('second_left', models.FloatField(verbose_name='测量次数二AA-BB内最大声压级（左侧）-SPL_L')),
                ('second_right', models.FloatField(verbose_name='测量次数二AA-BB内最大声压级（右侧）-SPL_R')),
                ('image', models.FileField(default=' ', upload_to='upload_image')),
                ('result', models.FloatField(verbose_name='通过噪声最终结果')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='汽车品牌')),
                ('clarity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clarity.clarity', verbose_name='语音清晰度')),
                ('loudness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loudness.loudness', verbose_name='响度')),
                ('sharpness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharpness.sharpness', verbose_name='尖锐度')),
                ('volatility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volatility.volatility', verbose_name='波动度')),
            ],
            options={
                'verbose_name': 'data',
                'verbose_name_plural': 'data',
                'db_table': 'data',
            },
        ),
    ]
