# Generated by Django 4.0.5 on 2023-09-21 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clarity', '0001_initial'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='clarity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clarity.clarity', verbose_name='语音清晰度'),
        ),
    ]
