# Generated by Django 4.0.5 on 2023-12-11 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0004_rename_clarity_total_clarity_result_and_more'),
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': '声压级结果', 'verbose_name_plural': '声压级结果'},
        ),
        migrations.RemoveField(
            model_name='data',
            name='clarity',
        ),
        migrations.RemoveField(
            model_name='data',
            name='image',
        ),
        migrations.RemoveField(
            model_name='data',
            name='loudness',
        ),
        migrations.RemoveField(
            model_name='data',
            name='power',
        ),
        migrations.RemoveField(
            model_name='data',
            name='result',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sharpness',
        ),
        migrations.RemoveField(
            model_name='data',
            name='volatility',
        ),
        migrations.AddField(
            model_name='data',
            name='data_image',
            field=models.FileField(default=' ', upload_to='upload_image', verbose_name='图片地址'),
        ),
        migrations.AddField(
            model_name='data',
            name='data_result',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='声压级最终结果'),
        ),
        migrations.AddField(
            model_name='data',
            name='total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='total.total', verbose_name='结果总表'),
        ),
        migrations.AlterField(
            model_name='data',
            name='car',
            field=models.CharField(default=' ', max_length=50, verbose_name='速度形式'),
        ),
        migrations.AlterField(
            model_name='data',
            name='condition',
            field=models.CharField(default=' ', max_length=100, verbose_name='工况'),
        ),
        migrations.AlterField(
            model_name='data',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='data',
            name='first_left',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='测量次数一AA-BB内最大声压级（左侧）-SPL_L'),
        ),
        migrations.AlterField(
            model_name='data',
            name='first_right',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='测量次数一AA-BB内最大声压级（右侧）-SPL_R'),
        ),
        migrations.AlterField(
            model_name='data',
            name='second_left',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='测量次数二AA-BB内最大声压级（左侧）-SPL_L'),
        ),
        migrations.AlterField(
            model_name='data',
            name='second_right',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='测量次数二AA-BB内最大声压级（右侧）-SPL_R'),
        ),
        migrations.AlterField(
            model_name='data',
            name='speed',
            field=models.CharField(default=' ', max_length=50, verbose_name='速度形式'),
        ),
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.CharField(default=' ', max_length=100, verbose_name='荷载状态'),
        ),
        migrations.AlterField(
            model_name='data',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
