# Generated by Django 4.0.5 on 2023-12-11 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_data_options_remove_data_clarity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='car',
        ),
        migrations.RemoveField(
            model_name='data',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='data',
            name='data_image',
        ),
        migrations.RemoveField(
            model_name='data',
            name='data_result',
        ),
        migrations.RemoveField(
            model_name='data',
            name='first_left',
        ),
        migrations.RemoveField(
            model_name='data',
            name='first_right',
        ),
        migrations.RemoveField(
            model_name='data',
            name='second_left',
        ),
        migrations.RemoveField(
            model_name='data',
            name='second_right',
        ),
        migrations.RemoveField(
            model_name='data',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='data',
            name='status',
        ),
    ]
