# Generated by Django 4.0.5 on 2023-09-29 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_alter_data_clarity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='clarity',
        ),
        migrations.RemoveField(
            model_name='data',
            name='loudness',
        ),
        migrations.RemoveField(
            model_name='data',
            name='power',
        ),
        migrations.RemoveField(
            model_name='data',
            name='sharpness',
        ),
        migrations.RemoveField(
            model_name='data',
            name='volatility',
        ),
    ]
