# Generated by Django 4.0.5 on 2023-09-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_image_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='data',
            name='image',
            field=models.FileField(default=' ', upload_to='upload_image'),
        ),
    ]
