# Generated by Django 4.1.12 on 2023-10-11 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_data_clarity_remove_data_loudness_and_more'),
        ('data', '0004_delete_image_data_image'),
    ]

    operations = [
    ]
