# Generated by Django 4.1.12 on 2023-10-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_options_alter_car_brand_alter_car_gear_and_more'),
        ('data', '0005_merge_20231012_0117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name': '声压级结果', 'verbose_name_plural': '声压级结果'},
        ),
        migrations.AlterField(
            model_name='data',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.car', verbose_name='汽车品牌'),
        ),
        migrations.AlterField(
            model_name='data',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工况'),
        ),
        migrations.AlterField(
            model_name='data',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='data',
            name='first_left',
            field=models.FloatField(blank=True, null=True, verbose_name='测量次数一AA-BB内最大声压级（左侧）-SPL_L'),
        ),
        migrations.AlterField(
            model_name='data',
            name='first_right',
            field=models.FloatField(blank=True, null=True, verbose_name='测量次数一AA-BB内最大声压级（右侧）-SPL_R'),
        ),
        migrations.AlterField(
            model_name='data',
            name='result',
            field=models.FloatField(blank=True, null=True, verbose_name='通过噪声最终结果'),
        ),
        migrations.AlterField(
            model_name='data',
            name='second_left',
            field=models.FloatField(blank=True, null=True, verbose_name='测量次数二AA-BB内最大声压级（左侧）-SPL_L'),
        ),
        migrations.AlterField(
            model_name='data',
            name='second_right',
            field=models.FloatField(blank=True, null=True, verbose_name='测量次数二AA-BB内最大声压级（右侧）-SPL_R'),
        ),
        migrations.AlterField(
            model_name='data',
            name='speed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='速度形式'),
        ),
        migrations.AlterField(
            model_name='data',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='荷载状态'),
        ),
        migrations.AlterField(
            model_name='data',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
