# Generated by Django 4.0.5 on 2023-12-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_alter_data_options_alter_data_car_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='image',
            field=models.FileField(default=' ', upload_to='upload_image', verbose_name='图片地址'),
        ),
    ]
