# Generated by Django 4.0.5 on 2023-09-29 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='gear',
            field=models.CharField(default=' ', max_length=50, verbose_name='档位形式'),
        ),
        migrations.AddField(
            model_name='car',
            name='power',
            field=models.CharField(default=' ', max_length=50, verbose_name='动力形式'),
        ),
    ]
