# Generated by Django 4.1.12 on 2023-10-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_gear_car_power'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': '车辆信息', 'verbose_name_plural': '车辆信息'},
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='品牌'),
        ),
        migrations.AlterField(
            model_name='car',
            name='gear',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='档位形式'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='车型'),
        ),
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='动力形式'),
        ),
    ]
