# Generated by Django 4.1.12 on 2023-10-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharpness', '0002_sharpness_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharpness',
            options={'verbose_name': '尖锐度数据', 'verbose_name_plural': '尖锐度数据'},
        ),
    ]
