"""
Django settings for ManageSystem project.

Generated by 'django-admin startproject' using Django 4.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-be0ecb-)q9xl!$dsben36fkqzu((@k3**)(1r_58^r2xeq=-mo'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'data',
    'loudness',
    'sharpness',
    'volatility',
    'clarity',
    'user',
    'car',
    'evaluation',
    'total'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ManageSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ManageSystem.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'ManageSystem',
        'USER': 'root',
        'HOST': '127.0.0.1',
        'POST': '3306',
        'OPTIONS': {
            "init_command": "SET foreign_key_checks = 0;",
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/


STATIC_URL = 'static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 换成自己Logo链接
SIMPLEUI_LOGO = '/static/images/logo.png'

# 隐藏右侧SimpleUI广告链接和使用分析
SIMPLEUI_HOME_INFO = False
SIMPLEUI_ANALYSIS = False

# 隐藏首页的快捷操作和最近动作
SIMPLEUI_HOME_QUICK = False
SIMPLEUI_HOME_ACTION = False

SIMPLEUI_CONFIG = {
    # 是否使用系统默认菜单，自定义菜单时建议关闭。
    'system_keep': False,

    # 用于菜单排序和过滤, 不填此字段为默认排序和全部显示。空列表[] 为全部不显示.
    'menu_display': ['实验数据', '车型管理', '用户管理'],

    # 设置是否开启动态菜单, 默认为False. 如果开启, 则会在每次用户登陆时刷新展示菜单内容。
    # 一般建议关闭。
    'dynamic': False,
    'menus': [
        {
            'app': 'data',
            'name': '实验数据',
            'icon': 'fa fa-th-list',

            'models': [
                {
                    'name': '声压级结果',
                    'icon': 'fa fa-tasks',
                    'url': 'data/data/'
                },
                {
                    'name': '响度数据',
                    'icon': 'fa fa-tasks',
                    'url': 'loudness/loudness/'
                },
                {
                    'name': '尖锐度数据',
                    'icon': 'fa fa-tasks',
                    'url': 'sharpness/sharpness/'
                },
                {
                    'name': '波动度数据',
                    'icon': 'fa fa-tasks',
                    'url': 'volatility/volatility/'
                },
                {
                    'name': '语言清晰度数据',
                    'icon': 'fa fa-tasks',
                    'url': 'clarity/clarity/'
                },
                {
                    'name': '声品质综合评价指数',
                    'icon': 'fa fa-tasks',
                    'url': 'evaluation/evaluation/'
                },
                {
                    'name': '结果总表',
                    'icon': 'fa fa-tasks',
                    'url': 'total/total/'
                },
            ]
        },

        {
            'app': 'car',
            'name': '车型管理',
            'icon': 'fa fa-th-list',

            'models': [
                {
                    'name': '车辆列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': 'car/car',
                    'icon': 'fa fa-tasks'
                },
            ]
        },
        {
            'app': 'user',
            'name': '用户管理',
            'icon': 'fa fa-th-list',
            'collapse': True,
            'models': [
                {
                    'name': '用户列表',
                    # 注意url按'/admin/应用名小写/模型名小写/'命名。
                    'url': 'user/user',
                    'icon': 'fa fa-tasks'
                },

            ]
        },
    ]
}

AUTH_USER_MODEL = 'user.User'

# 修改首页设置, 指向新创建的控制面板
SIMPLEUI_HOME_PAGE = '/ManageSystem/dashboard'
SIMPLEUI_HOME_TITLE = '主页'
SIMPLEUI_HOME_ICON = 'fa fa-eye'

# 导入导出
IMPORT_EXPORT_USE_TRANSACTIONS = True
