# Generated by Django 4.1.12 on 2023-10-11 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volatility', '0002_volatility_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volatility',
            options={'verbose_name': '波动度数据', 'verbose_name_plural': '波动度数据'},
        ),
    ]
