# Generated by Django 4.0.5 on 2023-12-11 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('total', '0004_rename_clarity_total_clarity_result_and_more'),
        ('clarity', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clarity',
            options={'verbose_name': '语言清晰度数据', 'verbose_name_plural': '语言清晰度数据'},
        ),
        migrations.RemoveField(
            model_name='clarity',
            name='car',
        ),
        migrations.RemoveField(
            model_name='clarity',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='clarity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='clarity',
            name='left',
        ),
        migrations.RemoveField(
            model_name='clarity',
            name='right',
        ),
        migrations.RemoveField(
            model_name='clarity',
            name='speed',
        ),
        migrations.RemoveField(
            model_name='clarity',
            name='status',
        ),
        migrations.AddField(
            model_name='clarity',
            name='total',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='total.total', verbose_name='结果总表'),
        ),
    ]
