# Generated by Django 4.1.12 on 2023-10-11 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clarity', '0002_clarity_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clarity',
            options={'verbose_name': '语言清晰度数据', 'verbose_name_plural': '语言清晰度数据'},
        ),
        migrations.AlterField(
            model_name='clarity',
            name='condition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='工况'),
        ),
        migrations.AlterField(
            model_name='clarity',
            name='left',
            field=models.FloatField(blank=True, null=True, verbose_name='语音清晰度度左耳-%'),
        ),
        migrations.AlterField(
            model_name='clarity',
            name='right',
            field=models.FloatField(blank=True, null=True, verbose_name='语音清晰度度右耳-%'),
        ),
        migrations.AlterField(
            model_name='clarity',
            name='speed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='速度形式'),
        ),
        migrations.AlterField(
            model_name='clarity',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='荷载状态'),
        ),
    ]
